### PR TITLE
created karate equivalent

### PR DESCRIPTION
**Pull request by ptrthomas**
Mark: I've added the [Karate](https://github.com/intuit/karate) equivalent of the tests.

This took me less than an hour to implement.  A few things I'd l like to call out (especially comparing this with REST-assured):
- no need to define request or response payload Java (POJO) objects
- in fact the data is expressed 'in-line', and the test is much more readable
- no need to create 'page object' representations of end-points as the HTTP operations boil down to one-liners
- lines 20, 39 and 40 in `api-test.feature` are proper validations (and access to data) you cannot do easily in REST-assured

I'd like to point you to this detailed comparison of Karate vs REST-assured: http://tinyurl.com/karatera - for your reference.

Hope you can add this to your project and blog / tweet about it !! Thanks for your time.

karate-vs-rest-assured

### CODE REVIEW

**Comment by mwinteringham** [comment]
Hi @ptrthomas I'm afraid this doesn't match the patterns I'm trying to achieve with this framework at this time. Here are my thoughts

1. First of all, I am reluctant to let in anything Gherkin based especially when the declared scenarios are very imperative in their steps. If you could update your steps to be more declarative and the feature file contains less 'code' that might make me feel more comfortable with merging
2. You have no single point for the models you've created for Booking and Payload. If I was to create a second feature file I assume I would have to add in more models/payloads into that feature file which doesn't make the framework DRY.
3. Additionally, this repo isn't about comparing technologies but promoting a design approach to API checking. I would appreciate it if you would remove any comments comparing this framework against others.

If you can resolve those issues I will take another look.

Mark

P.S: I appreciate I haven't made some of these points very clear in the readme so I've made a note to make some of these principles a bit clearer.

**Comment by ptrthomas** [comment]
@mwinteringham if you are reluctant to merge this, that's fine with me, but I'd like to respectfully disagree with your observations.

1. Karate is [imperative by design](https://hackernoon.com/yes-karate-is-not-true-bdd-698bf4a9be39), and should be considered on par with REST-assured as an alternative way to express API tests.
2. No, you can reuse JSON and feature files, again which differentiates Karate from Cucumber.
3. You may not need the overhead of design in some cases like I mentioned in my previous comment. So in my opinion this is a valid and very useful comparison that shows the impact on design that a framework choice implies.

**Comment by mwinteringham** [comment]
@ptrthomas so how would you go about reuse JSON? Perhaps you can update the code to demonstrate how that might work?

**Comment by ptrthomas** [comment]
@mwinteringham I think it is fine as it is, the `api-test.feature` is an exact port of `ApiTest.java`, and the re-use is already happening via a [variable called `payload`](https://github.com/mwinteringham/api-framework/pull/3/files#diff-44422e888067db4b7d43ccfa367b7afeR7).

Now if you had a second `ApiTest2.java`, I would be happy to make the change.

**Comment by mwinteringham** [comment]
@ptrthomas good point. I've had some requests about this framework demonstrating multiple APIs so I will have a look at that and then get back to you :)

**Pull request closed without merging**
